[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pork_staking = "5FVv4vXjWxenXoyGreTVXvqNoNWVnDrCCZnQPfvynhbj"

[programs.devnet]
pork_staking = "5FVv4vXjWxenXoyGreTVXvqNoNWVnDrCCZnQPfvynhbj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
